name: exam-portal
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: node ./backend/app.js
    ports:
      - 5000:5000
    depends_on:
      - mongodb
